name: Build and Release LaTeX PDF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up TeX Live
      uses: xu-cheng/texlive-action@v2
      with:
        texlive_version: "2023"
        scheme: "medium"  
        
    - name: Install missing LaTeX packages
      run: |
        tlmgr install algorithm algorithmic  # Install the required packages

    - name: Build LaTeX file
      run: |
        xelatex main.tex
        xelatex main.tex

    - name: Upload PDF as artifact
      uses: actions/upload-artifact@v4
      with:
        name: latex-pdf
        path: main.pdf

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create GitHub Release
      uses: gh-actions/create-release@v1
      with:
        tag_name: "v1.0.0"
        release_name: "Release LaTeX PDF"
        body: |
          PDF of the LaTeX build.
          The document can be downloaded [here](https://github.com/${{ github.repository }}/releases/download/v1.0.0/canggu.pdf)
    
    - name: Upload PDF to release
      uses: gh-actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: canggu.pdf
        asset_name: canggu.pdf
        asset_content_type: application/pdf
